/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appGraficaCliente;

import capaLogica.Cine;
import capaLogica.Cliente;
import capaLogica.Pelicula;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import appGraficaAdministrador.PrincipalCine;
import javax.swing.Icon;
import other.TipoTarjeta;
import other.Validaciones;

/**
 *
 * @author steve
 */
public class FrmReservar_Comprar extends javax.swing.JFrame {

    /**
     * Creates new form FrmReservar_Comprar
     */
    String asientos = "";
    Cliente oCliente;
    Cine cine;

    public FrmReservar_Comprar() {
        initComponents();
        oCliente = new Cliente();
        cine = new Cine();
    }

    //Llena el combo de películas
    private void cargarComboPelicula() {
        for (Pelicula pelicula : Cine.getArregloPelicula()) {
            if (pelicula == null) {
                continue;
            }

            jCboPeliculas.addItem(pelicula);
        }
    }

    //Llena el combo de los meses
    private void cargarComboMes() {
        for (int i = 1; i <= 12; i++) {
            jCboMes.addItem(i);
        }
    }

    //Carga el combo de los años
    private void cargarComboAnnio() {
        for (int i = 2020; i <= 2025; i++) {
            jCboAnnio.addItem(i);
        }
    }

    //Muestra las imagenes de la película
    private void muestraImagen() {
        int comboBox;
        comboBox = jCboPeliculas.getSelectedIndex();

        for (Pelicula pelicula : Cine.getArregloPelicula()) {
            if (pelicula.getNumeroSala() == comboBox + 1) {
                Icon j = new ImageIcon(pelicula.getUrlImagen());
                jLblImagenPelicula.setIcon(j);
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jBtnComprarBoletos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCboPeliculas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpnNinos = new javax.swing.JSpinner();
        jSpnAdultos = new javax.swing.JSpinner();
        jSpnAdultoMayor = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLblSubtotal = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtAsientosReservados = new javax.swing.JTextField();
        jLblImagenPelicula = new javax.swing.JLabel();
        jTxtRegresar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRdbVisa = new javax.swing.JRadioButton();
        jRdbMasterCard = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTxtCodigoSeguridad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCboMes = new javax.swing.JComboBox<>();
        jCboAnnio = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtNumeroTarjeta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservar y Comprar");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBtnComprarBoletos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnComprarBoletos.setText("Comprar boletos");
        jBtnComprarBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComprarBoletosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione la película: ");

        jCboPeliculas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCboPeliculas.setForeground(new java.awt.Color(153, 153, 0));
        jCboPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboPeliculasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione la catidad de boletos por edad: ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad de Niño:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad de Adulto:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de Adulto Mayor:");

        jSpnNinos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpnNinos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        jSpnAdultos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpnAdultos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        jSpnAdultoMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpnAdultoMayor.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        jLblSubtotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLblSubtotal.setForeground(new java.awt.Color(0, 153, 0));
        jLblSubtotal.setText("₡0.00");

        jBtnGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnGuardar.setText("Presione aquí para seleccionar sus asientos");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Reservaciones y compras");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Subtotal: ");

        jTxtAsientosReservados.setEditable(false);
        jTxtAsientosReservados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTxtAsientosReservados.setForeground(new java.awt.Color(255, 51, 51));
        jTxtAsientosReservados.setText("-- No hay asientos seleccionados, por favor selecciónelos --");
        jTxtAsientosReservados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAsientosReservadosActionPerformed(evt);
            }
        });

        jTxtRegresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTxtRegresar.setText("<Regresar");
        jTxtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRegresarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Asientos reservados:");

        jTxtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Tipo de tarjeta: ");

        jRdbVisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRdbVisa.setText("Visa");
        jRdbVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbVisaActionPerformed(evt);
            }
        });

        jRdbMasterCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRdbMasterCard.setText("Master Card");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Código de seguridad:");

        jTxtCodigoSeguridad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtCodigoSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoSeguridadActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("/");

        jCboMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCboAnnio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Fecha de vencimiento: ");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Año");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Mes");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Número de tarjeta:");

        jTxtNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumeroTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnComprarBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel6)))))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTxtAsientosReservados, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTxtCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTxtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jRdbVisa)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRdbMasterCard))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(30, 30, 30)
                                                .addComponent(jCboPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(149, 149, 149)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jSpnAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jSpnNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jSpnAdultoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLblSubtotal)))
                                        .addGap(371, 371, 371))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108)))
                                .addComponent(jLblImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCboAnnio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))))))
                    .addComponent(jTxtRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCboPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSpnNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jSpnAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jSpnAdultoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblSubtotal)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLblImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAsientosReservados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRdbVisa)
                    .addComponent(jRdbMasterCard))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnComprarBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jCboMes)
                                    .addComponent(jCboAnnio))))))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Carga los combos cuando la ventana se abre
        cargarComboPelicula();
        cargarComboMes();
        cargarComboAnnio();

        // Agrega los radios al grupo de botones 
        grupoBotones.add(jRdbVisa);
        grupoBotones.add(jRdbMasterCard);
        jRdbVisa.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

        // Obtener los valores que el usuario seleccionó en el spinner
        int cantidadNinos = (Integer) jSpnNinos.getValue();
        int cantidadAdultos = (Integer) jSpnAdultos.getValue();
        int cantidadAdultoMayor = (Integer) jSpnAdultoMayor.getValue();
        double montoTotal = oCliente.totalPagar(cantidadNinos, cantidadAdultos, cantidadAdultoMayor);
        int totalTiquetes = oCliente.totalTiquetes(cantidadNinos, cantidadAdultos, cantidadAdultoMayor);

        //Valida que los spinners no estén vacíos
        if ((Integer) jSpnNinos.getValue() == 0 && (Integer) jSpnAdultos.getValue() == 0 && (Integer) jSpnAdultoMayor.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un boleto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Se evalúa que el oCliente solo pueda comprar 4 boletos como máximo
        if (oCliente.validarCantidadBoletos(cantidadNinos, cantidadAdultos, cantidadAdultoMayor)) {
            JOptionPane.showMessageDialog(this, "Error, unicamente puede comprar 4 boletos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Se muestra el total a pagara en el label
        jLblSubtotal.setText("₡" + String.valueOf(montoTotal));

        /*Se pregunta al usuario que elija sus asientos, 
        * al darle aceptar se abre el frame con la matriz de botones
         */
        JOptionPane.showMessageDialog(this, "Por favor seleccione los asientos en los que desea reservar", "Seleccione asientos", JOptionPane.INFORMATION_MESSAGE);

        //Se crean las instancias.
        JDlgReservar jDlgDialog = new JDlgReservar(this, true, (Pelicula) jCboPeliculas.getSelectedItem(), totalTiquetes);
        jDlgDialog.setLocationRelativeTo(null);
        jDlgDialog.setVisible(true);

        //Se guardan los asientos seleccionados
        asientos = jDlgDialog.getAsientosReservados();

        //Luego se muestran al usuario los asientos que él seleccionó
        jTxtAsientosReservados.setText(asientos.substring(0, asientos.length() - 2));

        // Deshabilita el botón para que no pueda modificar la selección en caso de que ya haya seleccionado los asientos
        if (!asientos.equals("")) {
            jBtnGuardar.setEnabled(false);
            jBtnGuardar.setText("Ya seleccionó sus asientos");
        }


    }//GEN-LAST:event_jBtnGuardarActionPerformed


    private void jCboPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboPeliculasActionPerformed

        muestraImagen();
    }//GEN-LAST:event_jCboPeliculasActionPerformed

    private void jTxtAsientosReservadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAsientosReservadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAsientosReservadosActionPerformed

    private void jTxtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRegresarActionPerformed
        confirmarCerrar();
    }//GEN-LAST:event_jTxtRegresarActionPerformed

    private void jTxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreActionPerformed

    private void jBtnComprarBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComprarBoletosActionPerformed
        int cantidadNinos = (Integer) jSpnNinos.getValue();
        int cantidadAdultos = (Integer) jSpnAdultos.getValue();
        int cantidadAdultoMayor = (Integer) jSpnAdultoMayor.getValue();
        int totalTiquetes = cantidadNinos + cantidadAdultos + cantidadAdultoMayor;
        String numTarjeta = jTxtNumeroTarjeta.getText();
        numTarjeta = numTarjeta.replaceAll(" ", "");
        String nombre = jTxtNombre.getText();
        int annio = jCboAnnio.getSelectedIndex();
        int mes = jCboMes.getSelectedIndex();
        double total = oCliente.totalPagar(cantidadNinos, cantidadAdultos, cantidadAdultoMayor);
        int codeSeguridad = 0;

        if (Validaciones.hayNulosCompra(jTxtNombre.getText(), jTxtNumeroTarjeta.getText(), jTxtCodigoSeguridad.getText(), asientos)) {
            JOptionPane.showMessageDialog(null, "Error, " + Validaciones.getErrorMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Validaciones.validaTarjeta(jRdbVisa.isSelected(), jRdbMasterCard.isSelected(), numTarjeta, jTxtCodigoSeguridad.getText(), jCboAnnio.getSelectedIndex(), jCboMes.getSelectedIndex())) {
            JOptionPane.showMessageDialog(null, "Error, " + Validaciones.getErrorMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Valida que en el nombre solo se digiten letras
        if (!(nombre.matches("[a-zA-Z]{3,30}"))) {
            JOptionPane.showMessageDialog(null, "Nombre con formato inválido, solo debe digitar letras", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Instancia
        Cliente cliente = new Cliente(nombre, numTarjeta, annio, mes, codeSeguridad, total);
        cliente.setTotalBoletos(totalTiquetes);
        cliente.setPrecioTotal(total);

        //Validación si el usuario deja alguna caja de texto vacía
        /*isEmpty comprueba que la String asientos no esté vacía, si lo está
         *Retorna un true 
         *No se sale del if hasta que el usuario seleccione o digite los datos deseados
         */
        //
        //Selecciona los Radio Button
        cliente.setPelicula((Pelicula) jCboPeliculas.getSelectedItem());
        cliente.setAsientosReservados(JDlgReservar.getAsientosReservados());
        PrincipalCine.clienteActual = cliente;
        //Validación para que el usuario solo digite números enteros 
        //Envía un mensaje de confirmación si se desea continuar con la reservación
        int resultado = JOptionPane.showConfirmDialog(null, "¿Seguro que desea confirmar su reservación?");
        if (resultado == 0) // 0 = Sí. Guarda la reservación en la matriz
        {
            guardarReservacion();
        }


    }//GEN-LAST:event_jBtnComprarBoletosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Al confirmar se sale del programa
        confirmarCerrar();
    }//GEN-LAST:event_formWindowClosing
    private void confirmarCerrar() {
        //Pregunta si ya ha reservado asientos para cerrar
        if (jTxtAsientosReservados.getText().equals("-- No hay asientos seleccionados, por favor selecciónelos --")) {
            return;
        }

        int resultado = JOptionPane.showConfirmDialog(null, "Todavía no ha confirmado su reservación, ¿Seguro que desea salir?");
        if (resultado == JOptionPane.YES_OPTION) {
            // Libera los espacios reservados en la matriz en caso de que el usuario no haya confirmado la reservación
            cine.liberarReservacion(jCboPeliculas.getSelectedIndex());
            PrincipalCine.frmCine.setVisible(true);
            this.dispose();
        }
    }

    private void jRdbVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbVisaActionPerformed

    }//GEN-LAST:event_jRdbVisaActionPerformed

    private void jTxtCodigoSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoSeguridadActionPerformed

    private void jTxtNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumeroTarjetaActionPerformed

    //Este método se encarga de formalizar la reservación para que ya queden todos los datos almacenados en las celdas de la matriz
    private void guardarReservacion() {

        String[] asientoSeleccionado = asientos.split(" - ");
        String letras = "ABCDEFGHIJ";
        int fila = 0;
        int columna = 0;
        int sala = ((Pelicula) jCboPeliculas.getSelectedItem()).getNumeroSala();

        for (int i = 0; i < asientoSeleccionado.length; i++) {
            fila = letras.indexOf(asientoSeleccionado[i].charAt(0));
            columna = Character.getNumericValue(asientoSeleccionado[i].charAt(1));
            Cliente cliente = new Cliente();
            cliente.setNombreCliente(jTxtNombre.getText());

            // Se agregan los demás valores del ciente
            cine.confirmarReservacion(cliente, sala - 1, fila, columna - 1);
        }
        JOptionPane.showMessageDialog(this, "Reservación guardada exitosamente");
        PrincipalCine.jdlgFactura.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReservar_Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReservar_Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReservar_Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReservar_Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReservar_Comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jBtnComprarBoletos;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JComboBox<Integer> jCboAnnio;
    private javax.swing.JComboBox<Integer> jCboMes;
    private javax.swing.JComboBox<Pelicula> jCboPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblImagenPelicula;
    private javax.swing.JLabel jLblSubtotal;
    private javax.swing.JRadioButton jRdbMasterCard;
    private javax.swing.JRadioButton jRdbVisa;
    private javax.swing.JSpinner jSpnAdultoMayor;
    private javax.swing.JSpinner jSpnAdultos;
    private javax.swing.JSpinner jSpnNinos;
    private javax.swing.JTextField jTxtAsientosReservados;
    private javax.swing.JTextField jTxtCodigoSeguridad;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtNumeroTarjeta;
    private javax.swing.JButton jTxtRegresar;
    // End of variables declaration//GEN-END:variables
}
