/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appGraficaAdministrador;

public class FrmAdministrarCartelera extends javax.swing.JFrame {

    public FrmAdministrarCartelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuDefinirCartelera = new javax.swing.JMenuItem();
        jMnuEstadosSalas = new javax.swing.JMenuItem();
        jMnuCantAsientosReservados = new javax.swing.JMenuItem();
        jMnuRegresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Cartelera");
        setResizable(false);

        jMenu1.setText("Menú");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMnuDefinirCartelera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMnuDefinirCartelera.setText("Definir Cartelera");
        jMnuDefinirCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDefinirCarteleraActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuDefinirCartelera);

        jMnuEstadosSalas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMnuEstadosSalas.setText("Mostrar estados de las salas");
        jMnuEstadosSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEstadosSalasActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuEstadosSalas);

        jMnuCantAsientosReservados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMnuCantAsientosReservados.setText("Reporte de la cantidad de asientos reservados en cada sala");
        jMnuCantAsientosReservados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCantAsientosReservadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuCantAsientosReservados);

        jMnuRegresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMnuRegresar.setText("Regresar al menú anterior");
        jMnuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuRegresarActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuRegresar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuRegresarActionPerformed
        PrincipalCine.frmCine.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMnuRegresarActionPerformed

    private void jMnuCantAsientosReservadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCantAsientosReservadosActionPerformed
        PrincipalCine.jdlgCantidadAsientosOcupados.setVisible(true);
    }//GEN-LAST:event_jMnuCantAsientosReservadosActionPerformed

    private void jMnuDefinirCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDefinirCarteleraActionPerformed
        PrincipalCine.frmDefinirCartelera.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMnuDefinirCarteleraActionPerformed

    private void jMnuEstadosSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEstadosSalasActionPerformed
        PrincipalCine.jdlgEstadosSalas = new JDlgEstadosSalas(this, true);
        PrincipalCine.jdlgEstadosSalas.setLocationRelativeTo(null);
        PrincipalCine.jdlgEstadosSalas.setVisible(true);
    }//GEN-LAST:event_jMnuEstadosSalasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrarCartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuCantAsientosReservados;
    private javax.swing.JMenuItem jMnuDefinirCartelera;
    private javax.swing.JMenuItem jMnuEstadosSalas;
    private javax.swing.JMenuItem jMnuRegresar;
    // End of variables declaration//GEN-END:variables
}
