/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appGraficaAdministrador;

import capaLogica.Cine;
import capaLogica.Pelicula;
import java.awt.Image;
import java.io.File;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import other.Validaciones;

/**
 *
 * @author steve
 */
public class FrmDefinirCartelera extends javax.swing.JFrame {

    Pelicula pelicula;
    Cine cine;
    File archivo;
    String direccionImagen;

    public FrmDefinirCartelera() {
        initComponents();
        cine = new Cine();

        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtnRegresar = new javax.swing.JButton();
        jLblSala = new javax.swing.JPanel();
        jLblNombrePelicula = new javax.swing.JLabel();
        jTxtNombrePelicula = new javax.swing.JTextField();
        jCboSala = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLblHora = new javax.swing.JLabel();
        jTxtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtMinutos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcdFecha = new com.toedter.calendar.JCalendar();
        jLabel5 = new javax.swing.JLabel();
        jlblImagen = new javax.swing.JLabel();
        btnAgregarImagen = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Definir Cartelera");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite los datos de la película");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBtnRegresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        jBtnRegresar.setText("<Regresar");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jLblSala.setBackground(new java.awt.Color(255, 255, 255));
        jLblSala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLblSala.setForeground(new java.awt.Color(0, 0, 0));

        jLblNombrePelicula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblNombrePelicula.setForeground(new java.awt.Color(0, 0, 0));
        jLblNombrePelicula.setText("Nombre:");

        jTxtNombrePelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombrePeliculaActionPerformed(evt);
            }
        });

        jCboSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSalaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sala");

        jLblHora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblHora.setForeground(new java.awt.Color(0, 0, 0));
        jLblHora.setText("Horas:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Minutos:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Insertar Imagen");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAgregarImagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregarImagen.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarImagen.setText("Agregar");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLblSalaLayout = new javax.swing.GroupLayout(jLblSala);
        jLblSala.setLayout(jLblSalaLayout);
        jLblSalaLayout.setHorizontalGroup(
            jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLblSalaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLblSalaLayout.createSequentialGroup()
                        .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLblSalaLayout.createSequentialGroup()
                                .addComponent(jLblHora)
                                .addGap(26, 26, 26)
                                .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jTxtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLblSalaLayout.createSequentialGroup()
                                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboSala, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLblSalaLayout.createSequentialGroup()
                                        .addGap(393, 393, 393)
                                        .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLblSalaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)))))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jLblSalaLayout.createSequentialGroup()
                        .addComponent(jLblNombrePelicula)
                        .addGap(12, 12, 12)
                        .addComponent(jTxtNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        jLblSalaLayout.setVerticalGroup(
            jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLblSalaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLblSalaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLblNombrePelicula))
                    .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(4, 4, 4)
                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLblSalaLayout.createSequentialGroup()
                        .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLblSalaLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4))
                            .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLblSalaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jCboSala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jcdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLblSalaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jLblSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblHora)
                            .addComponent(jLabel3))))
                .addGap(56, 56, 56))
        );

        jlblImagen.getAccessibleContext().setAccessibleParent(this);

        jBtnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLblSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnRegresar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(513, 513, 513))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLblSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        PrincipalCine.frmAdministrar.setVisible(true);
        PrincipalCine.frmAdministrar.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jTxtNombrePeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombrePeliculaActionPerformed

    }//GEN-LAST:event_jTxtNombrePeliculaActionPerformed

    private void jCboSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSalaActionPerformed

    }//GEN-LAST:event_jCboSalaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LlenaComboSalas();
    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        int resultado;

        jDlgCargarArchivos cargarArchivos = new jDlgCargarArchivos(this, true);

        FileNameExtensionFilter formato = new FileNameExtensionFilter("JPG, PNG Y GIF", "jpg", "png", "gif");

        cargarArchivos.jFCImg.setFileFilter(formato);

        resultado = cargarArchivos.jFCImg.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == resultado) {
            archivo = cargarArchivos.jFCImg.getSelectedFile();
            direccionImagen = archivo.getAbsolutePath();

            try {

                ImageIcon imgIcon = new ImageIcon(archivo.toString());

                Icon icono = new ImageIcon(imgIcon.getImage().getScaledInstance(jlblImagen.getWidth(), jlblImagen.getHeight(), Image.SCALE_DEFAULT));

                jlblImagen.setIcon(icono);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al abrir: " + ex);
            }

        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

        if (Validaciones.hayNulos(jTxtNombrePelicula.getText(), jTxtHora.getText(), jTxtMinutos.getText(), direccionImagen)) {
            JOptionPane.showMessageDialog(null, Validaciones.getErrorMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Validaciones.validaFormato(jTxtNombrePelicula.getText())) {
            JOptionPane.showMessageDialog(null, Validaciones.getErrorMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Validaciones.esEnteroYFormatoCorrecto(jTxtHora.getText(), jTxtMinutos.getText())) {
            JOptionPane.showMessageDialog(null, Validaciones.getErrorMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombrePelicula = jTxtNombrePelicula.getText().trim();
        int numeroSala = (Integer) jCboSala.getSelectedItem();
        Date fecha = jcdFecha.getDate();
        int hora = Integer.parseInt(jTxtHora.getText());
        int minutos = Integer.parseInt(jTxtMinutos.getText());
        String urlImagen = direccionImagen;

        pelicula = new Pelicula(nombrePelicula, numeroSala, fecha, hora, minutos, urlImagen);

        if (cine.agregaPelicula(pelicula)) {
            JOptionPane.showMessageDialog(null, "Película agregada exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Se ha llegado al maximo de peliculas", "Información", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void limpiarCampos() {
        jTxtNombrePelicula.setText("");
        jTxtHora.setText("");
        jTxtMinutos.setText("");
        jlblImagen.setIcon(null);
    }

    private void LlenaComboSalas() {
        //Llena el combo de las salas
        for (int i = 1; i <= 3; i++) {
            jCboSala.addItem(i);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirCartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmDefinirCartelera().setVisible(true);

                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(FrmDefinirCartelera.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JComboBox jCboSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblHora;
    private javax.swing.JLabel jLblNombrePelicula;
    private javax.swing.JPanel jLblSala;
    private javax.swing.JTextField jTxtHora;
    private javax.swing.JTextField jTxtMinutos;
    private javax.swing.JTextField jTxtNombrePelicula;
    private com.toedter.calendar.JCalendar jcdFecha;
    private javax.swing.JLabel jlblImagen;
    // End of variables declaration//GEN-END:variables

}
